//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blcAPI2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incasari
    {
        public int c_id { get; set; }
        public Nullable<System.DateTime> C_AVANS_DATA { get; set; }
        public Nullable<decimal> C_AVANS { get; set; }
        public Nullable<System.DateTime> C_DATA_DIFERENTA { get; set; }
        public string C_FACTURA { get; set; }
        public string C_CHITANTA { get; set; }
        public int C_NUMAR { get; set; }
        public System.DateTime C_DATA { get; set; }
        public string P_NUME { get; set; }
        public string P_PRENUME { get; set; }
        public string P_TEL { get; set; }
        public Nullable<decimal> C_PRET { get; set; }
        public string L_NUME { get; set; }
    }
}
