//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blcAPI2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIBRARIE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LIBRARIE()
        {
            this.CONTRACTEs = new HashSet<CONTRACTE>();
            this.PERSOANEs = new HashSet<PERSOANE>();
            this.SERVICII_CONTRACT = new HashSet<SERVICII_CONTRACT>();
        }
    
        public int L_ID { get; set; }
        public string L_NUME { get; set; }
        public string L_TIP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRACTE> CONTRACTEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSOANE> PERSOANEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICII_CONTRACT> SERVICII_CONTRACT { get; set; }
    }
}
