//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blcAPI2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSOANE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSOANE()
        {
            this.CONTRACTEs = new HashSet<CONTRACTE>();
        }
    
        public int P_ID { get; set; }
        public string P_NUME { get; set; }
        public string P_PRENUME { get; set; }
        public string P_CNP { get; set; }
        public Nullable<int> P_ID_TYPE { get; set; }
        public Nullable<System.DateTime> P_DATA_NASTERII { get; set; }
        public string P_ADRESA { get; set; }
        public string P_JUDET { get; set; }
        public string P_ORAS { get; set; }
        public string P_TEL { get; set; }
        public string P_EMAIL { get; set; }
        public string P_ID_VALUE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRACTE> CONTRACTEs { get; set; }
        public virtual LIBRARIE LIBRARIE { get; set; }
    }
}
